export PATH="/usr/local/bin:./node_modules/.bin:$PATH"
export NODE_PATH=/usr/local/lib/node_modules
alias h='history'
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias l='ls'
alias ll='ls -F'
alias lll='ls -al'
alias editbash='nano ~/.bash_profile'
alias resource='source ~/.bash_profile && echo "Done!"'
alias gs='git status'
